
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module VGA_TEST(

	//////////// CLOCK //////////
	CLOCK_50, 	// BANK 4
	CLOCK2_50, 	// BANK 7
	CLOCK3_50, 	// BANK 3A

	//////////// KEY (Active Low) //////////
	KEY,
	
	SW,
	
	//////////// VGA //////////
	VGA_B,
	VGA_BLANK_N,
	VGA_CLK,
	VGA_G,
	VGA_HS,
	VGA_R,
	VGA_SYNC_N,
	VGA_VS,

	//////////// Fan Control //////////
	FAN_CTRL 
);

//=======================================================
//  PARAMETER declarations
//=======================================================


//=======================================================
//  PORT declarations
//=======================================================

//////////// CLOCK //////////
input 		          		CLOCK_50;
input 		          		CLOCK2_50;
input 		          		CLOCK3_50;

//////////// KEY (Active Low) //////////
input 		     [3:0]		KEY;

input 			  [17:0]    SW;

//////////// VGA //////////
output		     [7:0]		VGA_B;
output		          		VGA_BLANK_N;
output		          		VGA_CLK;
output		     [7:0]		VGA_G;
output		          		VGA_HS;
output		     [7:0]		VGA_R;
output		          		VGA_SYNC_N;
output		          		VGA_VS;

//////////// Fan Control //////////
inout 		          		FAN_CTRL;


//=======================================================
//  REG/WIRE declarations
//=======================================================
wire vidon_w;
wire hc_w;
wire vc_w;
wire pclock_w;

//=======================================================
//  Structural coding
//=======================================================

pixel_clock PCLOCK(
	.inclk0( CLOCK_50 ),
	.c0( pclock_w)
);

vga640x480 VGA(
	.CLK( pclock_w ),
	.CLR( ~KEY[0] ),
	.HSYNC( VGA_HS ),
	.VSYNC( VGA_VS ),
	.HC( hc_w ),
	.VC( vc_w ),
	.VIDON( vidon_w )
);

vga_stripes COLOR_GEN(
	.VIDON( vidon_w ),
	.HC( hc_w ),
	.VC( vc_w ),
	.R( VGA_R ),
	.G( VGA_G ),
	.B( VGA_B ),
	.SW( SW )
);


	//////////// FAN Control //////////
assign FAN_CTRL = 1'bz; // turn on FAN
assign VGA_BLANK_N = 1;
assign VGA_SYNC_N = 0;
assign VGA_CLK = pclock_w;

endmodule
