/*
	Module:       GPIO_TEST
	Description:  Tests snes_controller and nes_controller modules
	Author:       Sergio M, Randy T, Omar T, Hector D, Kevin M
	Date:         8/11/14
*/

//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================


module gpio_test(

	//////////// CLOCK //////////
	CLOCK_50, 	// BANK 4
	CLOCK2_50, 	// BANK 7
	CLOCK3_50, 	// BANK 3A

	//////////// LED (High Active) //////////
	LEDR,
	LEDG,

	//////////// GPIO, GPIO connect to GPIO Default //////////
	GPIO,

	//////////// Fan Control //////////
	FAN_CTRL 
);

//=======================================================
//  PARAMETER declarations
//=======================================================


//=======================================================
//  PORT declarations
//=======================================================

//////////// CLOCK //////////
input 		          		CLOCK_50;
input 		          		CLOCK2_50;
input 		          		CLOCK3_50;

//////////// LED (High Active) //////////
output		    [17:0]		LEDR;
output			 [7:0]		LEDG;

//////////// GPIO, GPIO connect to GPIO Default //////////
inout 		    [35:0]		GPIO;

//////////// Fan Control //////////
inout 		          		FAN_CTRL;

//=======================================================
//  REG/WIRE declarations
//=======================================================
wire [12:0] SNES_buttons;      // Holds the buttons for SNES Controller
wire [7:0]  NES_buttons;       // Holds the buttons for NES Controller

//=======================================================
//  Structural coding
//=======================================================

	//////////// FAN Control //////////
assign FAN_CTRL = 1'bz; // turn on FAN
assign LEDR     = SNES_buttons;
assign LEDG 	 = NES_buttons;

//SNES controller outputs to the LEDR
snes_controller player1( GPIO[31],   	// Latch
								 GPIO[35],   	// Data
								 GPIO[33],   	// Pulse
								 CLOCK_50,  	// CLOCK
								 SNES_buttons  // snes buttons
								);
								
//NES controller outputs to the LEDG
 nes_controller player2( GPIO[0],   	// Latch
								 GPIO[4],   	// Data
								 GPIO[2],   	// Pulse
								 CLOCK_50,  	// CLOCK
								 NES_buttons   // nes buttons
								);

endmodule
